#!/bin/sh
# - runtime
# - test
# - nr_task

## UnixBench is the original BYTE UNIX benchmark suite. The purpose
## of UnixBench is to provide a basic indicator of the performance
## of a Unix-like system; hence, multiple tests are used to test
## various aspects of the system's performance.

. $LKP_SRC/lib/debug.sh

cd $BENCHMARK_ROOT/unixbench || die "no $BENCHMARK_ROOT/unixbench"

if [ "$need_x" = true ]; then
	mkdir -p /tmp/.X11-unix
	chmod 1777 /tmp/.X11-unix
	chown root:root /tmp/.X11-unix

	xinit $LKP_SRC/programs/unixbench/xinitrc
else
	$LKP_SRC/programs/unixbench/xinitrc
fi
