AllCops:
  NewCops: disable
  SuggestExtensions: false

Metrics/MethodLength:
  Max: 50
  Enabled: false

Metrics/AbcSize:
  Max: 50
  Exclude:
    - lib/changed_stat.rb
    - lib/compare.rb
    - lib/dmesg.rb
    - lib/hash.rb
    - lib/job.rb
    - lib/job2sh.rb
    - lib/matrix.rb
    - lib/plot.rb
    - lib/stats.rb
    - sbin/compare

Metrics/BlockLength:
  Max: 50
  Exclude:
    - 'Rakefile'
    - '**/*.rake'
    - 'spec/**/*.rb'
  Enabled: false

Metrics/CyclomaticComplexity:
  Max: 30 # 6 by default
  Exclude:
    - lib/job2sh.rb
    - lib/matrix.rb
    - lib/stats.rb
    - sbin/compare

Metrics/PerceivedComplexity:
  Max: 30
  Exclude:
    - lib/job2sh.rb
    - lib/matrix.rb
    - lib/stats.rb
    - sbin/compare

Metrics/BlockNesting:
  Exclude:
    - lib/hash.rb
    - programs/suspend/parse

Metrics/ClassLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/EvalWithLocation:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/SafeNavigation:
  Enabled: false

Style/PerlBackrefs:
  Enabled: false

Style/RedundantBegin:
  Enabled: false

Style/RegexpLiteral:
  Enabled: false

Style/PercentLiteralDelimiters:
  Enabled: false

Style/GlobalVars:
  Enabled: false

Style/NumericPredicate:
  Exclude:
    - 'lib/job2sh.rb'
    - 'lib/matrix.rb'
    - 'lib/stats.rb'

# Style/MethodMissing:
#   Enabled: false

Style/MissingRespondToMissing:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Style/FloatDivision:
  Exclude:
    - 'programs/pmbench/parse'

# Required Ruby version: 2.6
Style/SlicingWithRange:
  Enabled: false

Security/Eval:
  Enabled: false

Security/JSONLoad:
  Enabled: false

Security/YAMLLoad:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Lint/ShadowingOuterLocalVariable:
  Enabled: false

# Required Ruby version: 2.6
Lint/ErbNewArguments:
  Enabled: false

Lint/RedundantCopDisableDirective:
  Enabled: false

Lint/FloatComparison:
  Enabled: false

Layout/LineLength:
  Enabled: false

# Layout/IndentFirstArrayElement:
#   Enabled: false

Layout/FirstArrayElementIndentation:
  Enabled: false

# Layout/IndentHeredoc:
#   Enabled: false

Layout/HeredocIndentation:
  Enabled: false

# Disable this temporarily to let rubocop 1.12.1 work with ruby3.2
Layout/BlockAlignment:
  Enabled: false

Naming/AccessorMethodName:
  Exclude:
    - 'lib/compare.rb'
    - 'lib/data_store.rb'
    - 'lib/nresult_root.rb'
    - 'lib/property.rb'
    - 'lib/result_root.rb'

Naming/MethodParameterName:
  Enabled: false

Naming/HeredocDelimiterNaming:
  Enabled: false

# # Required Ruby version: 2.4
# Performance/RegexpMatch:
#   Enabled: false
