#!/bin/sh

. $LKP_SRC/lib/detect-system.sh
detect_system

if [[ "$_system_version" = "2" ]]; then
    if ! rpm -q epel-release >/dev/null; then
	yum install -y epel-release
	yum makecache fast
    fi
    yum install -y $*
elif [[ "$_system_version" = "2022" ]]; then
    dnf -y install $*
fi
