#!/bin/sh
. $LKP_SRC/lib/common.sh

export PATH=$BENCHMARK_ROOT/filebench/bin:$PATH

task=$(cat /$TMP_RESULT_ROOT/filebench.task)
[ -n "$task" ] || {
        echo "filebench task file isn't setup properly!" >&2
        exit 1
}

. $LKP_SRC/lib/reproduce-log.sh

$task
exit_status=$?

mntpoint=${mount_points%% *}
# Remove all files/directories created by test
ls -d ${mntpoint:?}/*
log_cmd rm -rf ${mntpoint:?}/*

exit $exit_status
