#!/bin/bash
# - group

. $LKP_SRC/lib/reproduce-log.sh
. $LKP_SRC/lib/tests/version.sh
. $LKP_SRC/lib/detect-system.sh

arch=$(get_system_arch)

if [[ "$group" = "group-00" ]]; then
	test_array=("bitfield_kunit" "test_bits" "cmdline_kunit" "ext4-inode-test" "test_hash" \
	            "test_linear_ranges" "list-test" "memcpy_kunit" "dev_addr_lists_test" "resource_kunit" \
	            "lib_test" "sysctl-test" "time_test" "test_list_sort" "test_sort" "fat_test" "kasan_test" \
	            "kfence_test" "mptcp_crypto_test" "mptcp_token_test" "rational-test" "slub_kunit" \
	            "apparmor_policy_unpack_test" "fortify_kunit" \
	            "drm_cmdline_parser_test" "drm_damage_helper_test" "drm_dp_mst_helper_test" "drm_mm_test" \
	            "drm_format_helper_test" "drm_format_test" "drm_framebuffer_test" "drm_plane_helper_test" "drm_rect_test")
elif [[ "$group" = "group-01" ]]; then
	# test_kstrtox: could not insert 'test_kstrtox': Invalid argument
	# test_string_helpers: could not insert 'test_string_helpers': Invalid argument
	# test_overflow: Module test_overflow not found in directory /lib/modules/6.0.0-rc5
	# test_ida: could not insert 'test_ida': Invalid argument
	# udelay_test: Module udelay_test not found in directory /lib/modules/6.0.0-rc5
	# test_vmalloc: could not insert 'test_vmalloc': Resource temporarily unavailable
	# test_klp_state: could not insert 'test_klp_state': Invalid argument
	# test_meminit: could not insert 'test_meminit': Invalid argument
	test_array=("test_string" "test_div64" "test_bpf" "test_min_heap" "test_user_copy" "test_static_key_base" \
	            "test_scanf" "test_printf" "test_bitmap" "test_uuid" "test_xarray" "test_rhashtable" "test_memcat_p" \
	            "test_udelay" "test_klp_livepatch" "test_klp_shadow_vars" "test_hmm" "test_free_pages" "test_fpu" \
	            "test_bitops" "test_async_driver_probe" "spi-loopback-test" "globtest" \
	            "crc32test" "atomic64_test" "test_maple_tree" "snd-soc-avs-i2s-test" "test_dynamic_debug")
elif [[ "$group" = "group-02" ]]; then
	test_array=("clk-gate_test" "clk_test" "cpumask_kunit" "cros_kunit" "hid-uclogic-test" "iio-test-format" \
	            "iio-test-rescale" "overflow_kunit" "soc-utils-test" "stackinit_kunit" "is_signed_type_kunit" \
	            "kmsan_test" "siphash_kunit" "strscpy_kunit")
elif [[ "$group" = "group-03" ]]; then
	test_array=("drm_buddy_test")
fi

run_kunit_tests()
{
	for i in ${test_array[@]}; do
		# f7e01ab828fd4 kasan: move tests to mm/kasan/
		# kasan unit test is renamed from test_kasan to kasan_test by above commit merged in v6.1-rc1
		[[ $i = kasan_test ]] && {
			if modprobe -q -n kasan_test; then
				i=kasan_test
			elif modprobe -q -n test_kasan; then
				i=test_kasan
			else
				echo 'kasan unit test module is not found' >&2
				continue
			fi
		}
		[[ $i =~ "drm_" || $i =~ "cpumask_kunit" ]] && {
			if ! is_kernel_version_gt 6.0; then
				# skip not exist module
				continue
			fi
		}
		[[ $arch = "i386" ]] && {
			# skip TEST_LIVEPATCH related modules
			[[ $i = test_klp_livepatch ]] && continue
			[[ $i = test_klp_shadow_vars ]] && continue
			# skip TEST_HMM related module
			[[ $i = test_hmm ]] && continue
		}
		[[ $i =~ "clk" || $i =~ "overflow_kunit" || $i =~ "stackinit_kunit" ]] && {
			if ! is_kernel_version_ge 5.18; then
				# skip not exist module
				continue
			fi
		}
		[[ $i =~ "soc-utils-test" ]] && {
			if ! is_kernel_version_ge 5.19; then
				# skip not exist module
				continue
			fi
		}
		[[ $i =~ "cros_kunit" || $i =~ "iio-test-format" || $i =~ "iio-test-rescale" || $i =~ "snd-soc-avs-i2s-test" ]] && {
			if ! is_kernel_version_ge 6.0; then
				# skip not exist module
				continue
			fi
		}
		[[ $i =~ "hid-uclogic-test" ]] && {
			if ! is_kernel_version_ge 6.1; then
				# skip not exist module
				continue
			fi
		}
		log_cmd modprobe $i
		log_cmd rmmod $i
	done
}

run_kunit_tests
dmesg > "$TMP_RESULT_ROOT"/kunit
