#!/bin/sh
# - runtime
# - seed
# - number

## perf_fuzzer is a system call fuzzer specifically designed
## to find flaws in the complex Linux perf_event system call interface.
## See: https://github.com/deater/perf_event_tests/tree/master/fuzzer

. $LKP_SRC/lib/reproduce-log.sh

cd $BENCHMARK_ROOT/perf_event_tests/fuzzer || die "can not find fuzzer dir"

# Check parameters
[ -z "$number" ] && [ -z "$runtime" ] && die "number and runtime can not both be empty "

# Generate seed
[ -z "$seed" ] && {
	seed_source="$tbox_group/$rootfs/$kconfig"

	if has_cmd cksum; then
		seed=$(echo "$seed_source" | cksum)
		seed=${seed%% *}
	else
		seed=$(echo "$seed_source" | md5sum | cut -c1-5)
		seed=$(( 0x$seed ))
	fi

	echo "Seeding perf-fuzzer by $seed based on $seed_source"
}

# Run test
opt="-r $seed"
[ -n "$number" ] && opt="$opt -s $number"
log_cmd ./perf_fuzzer $opt &

# Wait test finish or timeout
pid=$!
if [ -n "$runtime" ]; then
	sleep "$runtime"
	kill -9 "$pid" 2>&1
else
	wait "$pid" 2>&1
fi
