#!/bin/sh
# - nr_processes

## The mpirun command controls several aspects of program
## execution in Open MPI. mpirun uses the Open Run-Time
## Environment (ORTE) to launch jobs.

cd /tmp || exit
log_cmd cp -a /usr/share/doc/hpcc/examples/_hpccinf.txt hpccinf.txt

[ -n "$nr_processes" ] || nr_processes=$nr_cpu

log_cmd orterun --allow-run-as-root -np $nr_processes hpcc

cat /tmp/hpccoutf.txt
