#!/usr/bin/env ruby

LKP_SRC = ENV['LKP_SRC'] || File.dirname(File.dirname(File.realpath($PROGRAM_NAME)))

require "#{LKP_SRC}/lib/tests/stats"

stats = LKP::Stats.new

while (line = $stdin.gets)
  case line
  when /([\d.]+:) (.*): FAILED!$/
    stats.add $2, 'fail'
  when /([\d.]+:) (.*): Ok$/
    stats.add $2, 'pass'
  when /([\d.]+:) (.*): (Skip$|Skip .*)/
    stats.add $2, 'skip'
  when /ignored_by_lkp: (.*)/
    stats.add $1, 'ignored_by_lkp'
  when /sudo \/usr\/src\/perf_selftests-\S+ test \d+/
    # 2021-02-10 21:30:02 sudo /usr/src/perf_selftests-x86_64-rhel-8.3-*/tools/perf/perf test 32
    stats.add 'perf.make', 'pass' unless stats.key?('perf.make')
  when /make perf failed/
    stats.add 'perf.make', 'fail'
  end
end

stats.dump
