suite: kbuild
testcase: kbuild
category: benchmark

runtime: 300s

nr_task:
  - 200%
  - 50%

target: autoksyms_recursive

build_kconfig:
  - allyesconfig
  - defconfig

kbuild:

---
disk: 1HDD
fs:
  - ext4
  - btrfs
