#!/bin/sh
# - nr_processes
# - nr_threads
# - mem_proc
# - extra_params

## perf began as a tool for using the performance counters
## subsystem in Linux, and has had various enhancements
## to add tracing capabilities.

. $LKP_SRC/lib/unit.sh
. $LKP_SRC/lib/reproduce-log.sh

[ -n "$nr_processes" ] || nr_processes=$nr_cpu

mb_proc=$(to_mb $mem_proc)

log_cmd numactl --hard || die "Test needs available numa"

log_cmd perf bench numa mem -p $nr_processes -t $nr_threads -m -0 -P $mb_proc $extra_params
